name: ESLint

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npx eslint --ext .ts --ext .tsx src/
