on: push

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npx eslint --ext .ts --ext .tsx src/

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npx prettier --check .

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build:ts
