on: push

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm test

  deploy:
    needs: test

    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: "deploy-to-pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-pages-artifact@v2
        with: { path: "dist" }

      - uses: actions/deploy-pages@v2
        id: deployment
