name: Build and deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git name and email
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "no-reply@github-actions-bot"

      - name: Install, build and deploy
        run: |
          npm i --only=prod
          npm run deploy
