on:
  push:
    branches:
      - develop

jobs:
  visualize-repo:
    name: Visualize repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: githubocto/repo-visualizer@0.9.1
